#!/bin/bash
set -u -e -E -C -o pipefail

virtualenv ve
set +u
. ve/bin/activate 
set -u

(
    cd ve/lib/python*/site-packages/
    ln -sf ../../../../src/main/python/* .
)
(
    cd ve/bin/ 
    ln -sf ../../src/main/scripts/* .
)

pip install pybuilder || :
if ! pip install pygraphviz; then
    echo "pygraphviz could not be installed!"
    echo "perhaps you have to install graphviz and libgraphviz-dev."
fi
