#!/bin/bash
set -u -e -E -C -o pipefail

sudo apt-get install python-virtualenv

virtualenv ve
set +u
. ve/bin/activate
set -u

BP_TOP_DIR=$(dirname $PWD)

(
    cd ve/lib/python*/site-packages/
    rm -rf bigpicture
    mkdir bigpicture
    cd bigpicture
    ln -sf $BP_TOP_DIR/common/src/main/python/bigpicture/* .
    ln -sf $BP_TOP_DIR/analyse-data/src/main/python/bigpicture/analysedata .
)
(
    cd ve/bin/
    ln -sf ../../src/main/scripts/* .
)

sudo apt-get install graphviz
sudo apt-get install python-pygraphviz
sudo apt-get install pdsh

pip install pybuilder || :
if ! pip install pygraphviz; then
    echo "pygraphviz could not be installed!"
    echo "perhaps you have to install graphviz and libgraphviz-dev."
fi

pip install docopt
pip install py2neo
pip install networkx
pip install numpy
pip install --upgrade distribute
pip install matplotlib

cat <<WELCOME

The virtualenv for the bigpicture project was generated successfully.

Remember to 'source ve/bin/activate' before work.

WELCOME

