#!/usr/bin/env python
"""
Usage:
    build-live-model [--data-dir=<DATA_DIR>] [--model-file=<MODEL_FILE>]

Options:
    --data-dir=<DATA_DIR>           where to get the live data (should end with "live-data/")
    --model-file=<MODEL_FILE>       where to store the generated model file

When not given on command line, options are taken from /etc/bigpicture.conf.d/settings.ini
"""

import glob
import os

from docopt import docopt

from bigpicture import retrieve_config
from bigpicture.analysedata import netstats2dot, makedirs

arguments = docopt(__doc__)

data_dir = retrieve_config('data-dir', arguments, 'live-state')
model_file = retrieve_config('model-file', arguments, 'live-state')

print "building model from live data"

print "-- settings"
print "---- data dir: %s" % data_dir
print "---- model file: %s" % model_file

input_files = glob.glob(os.path.join(data_dir, "*", "*"))
print "---- %i input files found" % len(input_files)

print "-- creating model"
makedirs(os.path.dirname(model_file))
with open(model_file, 'w') as mf:
    mf.write(netstats2dot(input_files))

print "---- %s generated" % model_file
print "done."
