#!/usr/bin/env python
"""
Usage:
    convert_model [--model-file=<MODEL_FILE>] [--model-reduced-dot-file=<REDUCED_DOT_MODEL>] [--model-gexf-file=<STRING>] [--model-reduced-gexf-file=<REDUCED_GEXF_MODEL>] [--json-file=<STRING>] [--ssh-query-host=<HOSTNAME>]

When not given on command line, options are taken from /etc/bigpicture.conf.d/settings.ini
"""
import os

import networkx as nx

from docopt import docopt

from bigpicture import retrieve_config, init_config, makedirs
from bigpicture.analysedata.dot import model2json


def get_graph_stats(filename, g):
    return "%s, %s nodes, %s edges" % (type(g), g.number_of_nodes(), g.size())

arguments = docopt(__doc__)

init_config({'variant': 'all'})

model_file = retrieve_config('model-file', arguments, 'live-state')
reduced_dot_file = retrieve_config('model-reduced-dot-file', arguments, 'live-state')
gexf_file = retrieve_config('model-gexf-file', arguments, 'live-state')
reduced_gexf_file = retrieve_config('model-reduced-gexf-file', arguments, 'live-state')
json_file = retrieve_config('json-file', arguments, 'live-state')

print "augmenting/reducing model, generating different formats for post-processing"

print "-- settings"
print "---- model: %s" % model_file
print "---- reduced dot model: %s" % reduced_dot_file
print "---- gexf model: %s" % gexf_file
print "---- reduced gexf model: %s" % reduced_gexf_file
print "---- json model: %s" % json_file

print "-- loading model"
g = nx.drawing.read_dot(model_file)
print "---- %s" % get_graph_stats(model_file, g)

query_host = retrieve_config('ssh-query-host', arguments, 'live-state')
if query_host:
    print "-- removing ssh connections from query host %s" % query_host
    to_be_removed = set()
    for u, v, d in g.edges_iter(data=True):
        if d['protocol'] != 'ssh':
            continue
        if u == query_host:
            to_be_removed.add((u, v))
    g.remove_edges_from(to_be_removed)
    print "---- %s" % get_graph_stats(model_file, g)

print "-- creating reduced copy"
h = nx.DiGraph(g)
print "---- %s" % get_graph_stats(reduced_dot_file, h)

print "-- storing new models"
print "---- writing %s" % reduced_dot_file
makedirs(os.path.dirname(reduced_dot_file))
nx.drawing.write_dot(h, reduced_dot_file)

print "---- writing %s" % gexf_file
makedirs(os.path.dirname(gexf_file))
nx.write_gexf(g, gexf_file)

print "---- writing %s" % reduced_gexf_file
makedirs(os.path.dirname(reduced_gexf_file))
nx.write_gexf(h, reduced_gexf_file)

print "---- writing %s" % json_file
makedirs(os.path.dirname(json_file))
model2json(h, json_file)

print "done."
