#!/bin/bash

SOURCE=bigpicture.md
OUTDIR=out

REVEALJSDIR=$OUTDIR/reveal.js

IMPRESSDIR=$OUTDIR/impress.js
IMPRESSTEMPLATEDIR=$OUTDIR/5665065

AVALANCHEDIR=$OUTDIR/avalanche


mkdir -p $OUTDIR

[[ -d $REVEALJSDIR ]] || git clone https://github.com/hakimel/reveal.js.git $REVEALJSDIR
pandoc -t revealjs -o $OUTDIR/bigpicture.reveal.html -s $SOURCE


[[ -d $IMPRESSDIR ]] || git clone https://github.com/bartaz/impress.js.git $IMPRESSDIR
[[ -d $IMPRESSTEMPLATEDIR ]] || git clone https://gist.github.com/5665065.git $IMPRESSTEMPLATEDIR
cp $SOURCE $OUTDIR
(
    cd $OUTDIR
    pandoc --template 5665065/impress-template.html -V impress-url=impress.js -s -t html5 --section-divs -o bigpicture.impress.html $SOURCE
    #pandoc --template 5665065/impress-template.html -V impress-url=impress.js -s -t html5 -o bigpicture.impress.html $SOURCE
    rm -f $SOURCE
)

landslide -h > /dev/null 2>&1 || sudo apt-get install python-landslide
[[ -d $AVALANCHEDIR ]] || git clone https://github.com/akrabat/avalanche.git $AVALANCHEDIR
landslide bigpicture.cfg
