#!/usr/bin/env python

import string
import sys
import re
import os

print "{"
lb=""

for filename in sys.argv[1:]:
  with open(filename) as f:
      for line in f:
          match=re.match('address',string.strip(line))
          if match :
              sp=string.strip(line).split()
              sys.stdout.write( '%s"%s": "%s"' %(lb, sp[1],os.path.basename(filename) ) )
              lb=",\n"
print "\n}"
