#!/usr/bin/env python
"""
Usage:
    fetch_live_data [--data-dir=<DATA_DIR>] [--parallel=<PARALLEL>] [--now=<NOW>] [<host>...]

Options:
    -h --help               Show this help.
    --data-dir=<DATA_DIR>   where should the data be stored
    --parallel=<PARALLEL>   start PARALLEL threads for querying [default: 2]
    --now=<NOW>             uses <NOW> as timestamp

When not given on command line, options are taken from /etc/bigpicture.conf.d/settings.ini
"""

import sys

from docopt import docopt

from bigpicture import retrieve_config
from bigpicture.fetchdata import fetch_live_data

arguments = docopt(__doc__)

data_dir = retrieve_config('data-dir', arguments, 'live-state')

hosts = arguments['<host>']
if not hosts:
    hosts = sys.stdin.readlines()
hosts = [h for line in hosts for h in line.rstrip().split()]

print "fetching live data (netstat and mount, via pdsh)"

print "-- settings"
print "---- data dir: %s" % data_dir
print "---- nr hosts: %i" % len(hosts)
print "---- parallel: %s" % arguments['--parallel']
print "-- fetching live data"
fetch_live_data(hosts, data_dir, arguments['--parallel'], arguments['--now'])

print "done."
