#!/usr/bin/env python
import json

import pygraphviz

import bigpicture


with open(bigpicture.MAPPING_FILE) as mapping_file:
    mapping = json.load(mapping_file)

g = pygraphviz.AGraph(bigpicture.DOT_FILE)
h = g.copy()
h.clear()

for edge in g.edges_iter():
    def calc_label(s):
        if s in mapping:
            return "%s %s" % (mapping[s], s)
        return s
    source = calc_label(edge[0])
    target = calc_label(edge[1])
    h.add_edge(source, target, **edge.attr)

h.write(bigpicture.DOT_FILE)
