#!/usr/bin/env python
"""
Usage:
    augment_model [DOTFILE] [options]

Options:
    --ip-mappings=file  maps ips to hostnames [default: data/ip_host.mapping]
"""
import json
import pygraphviz
from docopt import docopt

import bigpicture


options = docopt(__doc__)
if not options["DOTFILE"]:
    options["DOTFILE"] = bigpicture.DOT_FILE
print options

with open(options["--ip-mappings"]) as mapping_file:
    mapping = json.load(mapping_file)

g = pygraphviz.AGraph(options["DOTFILE"])
h = g.copy()
h.clear()

for edge in g.edges_iter():
    def calc_label(s):
        if s in mapping:
            #return "%s %s" % (mapping[s], s)
            return mapping[s]
        return s
    source = calc_label(edge[0])
    target = calc_label(edge[1])
    h.add_edge(source, target, **edge.attr)

h.write(options["DOTFILE"])
