#!/usr/bin/env python
import glob
import os
import sys

import bigpicture

input_files = sys.argv[1:]
if not input_files:
    input_files = glob.glob(os.path.join(bigpicture.OUT_DIR, "actual_state", "*", "*", "netstat"))

with open(bigpicture.DOT_FILE, "w") as model_file:
    model_file.write(bigpicture.netstats2dot(input_files))
