#!/usr/bin/env python
import argparse
import sys

from bigpicture import fetch_data

parser = argparse.ArgumentParser()
parser.add_argument("-j", "--jump-host", dest="jumphost")
parser.add_argument("-p", "--parallel", dest="parallel", default=2)
parser.add_argument("hosts", nargs="*")

args = parser.parse_args()
if not args.hosts:
    args.hosts = sys.stdin.readlines()
hosts = [h for line in args.hosts for h in line.rstrip().split()]

fetch_data(hosts, args.jumphost, args.parallel)
