#!/usr/bin/env python
"""lookup_ips

Usage:
      lookup_ips [ -j jumphost ] INPUT_FILE ...

Options:

      -j, --jump-host JUMPHOST    use jumphost
"""
import json
import re
from   docopt import docopt

import bigpicture
import bigpicture.dot

options = docopt(__doc__)

ips = set()
for filename in options["INPUT_FILE"]:
    if filename.endswith(".dot"):
        print "parsing dot file %s" % filename
        ips = ips.union(bigpicture.dot.extract_ips_from_dot_file(filename))
    else:
        print "assuming mapping in %s" % filename
        with open(filename) as mapping_file:
            mapping = json.load(mapping_file)
            ips = ips.union(mapping.keys())

ips = [ip for ip in ips if not re.search("[a-zA-Z]", ip) or not re.search("\.", ip)]

mapping_filename = bigpicture.MAPPING_FILE
print mapping_filename

#mappings = bigpicture.lookup_ips(ips, options["--jump-host"])
with open(mapping_filename) as mapping_file:
    mappings = json.load(mapping_file)

for value in mappings.values():
    new_key = value.split(".", 1)[0]
    if new_key:
        mappings[new_key] = value

with open(mapping_filename, "w") as mapping_file:
    json.dump(mappings, mapping_file, indent=4, sort_keys=True)


