#!/usr/bin/env python
import argparse
import json

import bigpicture
import bigpicture.dot


parser = argparse.ArgumentParser()
parser.add_argument("-j", "--jump-host", dest="jumphost")

args = parser.parse_args()

with open(bigpicture.MAPPING_FILE, "w") as mapping_file:
    mappings = bigpicture.lookup_ips(bigpicture.dot.extract_ips(), args.jumphost)
    json.dump(mappings, mapping_file)
