#!/usr/bin/env python

"""
Usage:
    shorten_names DOT_FILE
"""

import logging
import pygraphviz
from docopt import docopt
import re

logging.basicConfig(level=logging.INFO)

options = docopt(__doc__)
dot_file = options["DOT_FILE"]
new_dot_file = re.sub("\.dot", ".shorter_names.dot", dot_file)

graph = pygraphviz.AGraph(dot_file)

def shorten_name(name):
    first_token = name.split(".")[0]
    if not first_token:
        return name
    return first_token[0:6]

ng = graph.copy()
ng.clear()
for edge in graph.edges():
    try:
        ng.add_edge(shorten_name(edge[0]), shorten_name(edge[1]), **edge.attr)
    except TypeError as e:
        logging.error("cannot shorten edge %s -> %s" % edge)

graph = ng

graph.write(new_dot_file)
